#!/usr/bin/env python3
"""
Population-over-landscape GIFs for all three optimizers (NSGA-II, PSO, SGA).

Each GIF overlays individuals (or particles) on the same 2D bit-layout heatmap
as the original single-GA animation. NSGA-II and PSO use *_snapshots.csv; SGA
uses per-generation CSVs under output/sga/anim/ (id, fitness).

Run from the repository root after ./run.sh has produced outputs, or after
plot_landscape.py --triangle (so figures/triangle_n16_m1_s4.csv exists).
"""

from __future__ import annotations

import argparse
import glob
import os
import re

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.animation import FuncAnimation
from scipy.ndimage import gaussian_filter

# Per dataset: bit width, column index of fitness in landscape CSV, paths.
# Landscape CSVs: HDF5 exports use mean_accuracy at column index 3.
# Triangle reference CSV is generated by plot_landscape.py --triangle --save figures
CASES: list[dict] = [
    {
        "name": "breast",
        "bits": 9,
        "fit_col": 3,
        "landscape": "output/breast-w.csv",
        "nsga_snapshots": "output/breast-w_snapshots.csv",
        "pso_snapshots": "output/pso-breast-w_snapshots.csv",
        "sga_anim_dir": "output/sga/anim",
    },
    {
        "name": "credit",
        "bits": 15,
        "fit_col": 3,
        "landscape": "output/credit-a.csv",
        "nsga_snapshots": "output/credit-a_snapshots.csv",
        "pso_snapshots": "output/pso-credit-a_snapshots.csv",
        "sga_anim_dir": "output/sga/anim",
    },
    {
        "name": "letter",
        "bits": 16,
        "fit_col": 3,
        "landscape": "output/letter-r.csv",
        "nsga_snapshots": "output/letter-r_snapshots.csv",
        "pso_snapshots": "output/pso-letter-r_snapshots.csv",
        "sga_anim_dir": "output/sga/anim",
    },
    {
        "name": "triangle",
        "bits": 16,
        "fit_col": 3,
        "landscape": "figures/triangle_n16_m1_s4.csv",
        "nsga_snapshots": "output/triangle_snapshots.csv",
        "pso_snapshots": "output/pso-triangle_snapshots.csv",
        "sga_anim_dir": "output/sga/anim",
    },
]


def landscape_grid(csv_path: str, bits: int, fit_col: int):
    """Return (grid, grid_h, grid_w, lower) for 2D bit-layout imshow."""
    df = pd.read_csv(csv_path)
    upper = bits // 2
    lower = bits - upper
    grid_h = 1 << upper
    grid_w = 1 << lower

    fitness = np.zeros(1 << bits)
    for _, row in df.iterrows():
        idx = int(row.iloc[0])
        fitness[idx] = float(row.iloc[fit_col])

    grid = np.zeros((grid_h, grid_w))
    for i in range(len(fitness)):
        grid[i >> lower, i & ((1 << lower) - 1)] = fitness[i]
    return grid, grid_h, grid_w, lower


def frames_from_sga(anim_dir: str, case_name: str) -> list[tuple[int, pd.DataFrame]]:
    pattern = os.path.join(anim_dir, f"{case_name}_gen_*.csv")
    files = sorted(glob.glob(pattern), key=lambda p: int(re.search(r"gen_(\d+)", p).group(1)))
    out: list[tuple[int, pd.DataFrame]] = []
    for path in files:
        gen = int(re.search(r"gen_(\d+)", path).group(1))
        df = pd.read_csv(path)
        if "id" not in df.columns and "index" in df.columns:
            df = df.rename(columns={"index": "id"})
        out.append((gen, df[["id"]]))
    return out


def frames_from_snapshots(csv_path: str) -> list[tuple[int, pd.DataFrame]]:
    if not os.path.isfile(csv_path):
        return []
    df = pd.read_csv(csv_path)
    if "generation" not in df.columns or "index" not in df.columns:
        return []
    frames: list[tuple[int, pd.DataFrame]] = []
    for gen in sorted(df["generation"].unique()):
        sub = df.loc[df["generation"] == gen, ["index"]].copy()
        sub = sub.rename(columns={"index": "id"})
        frames.append((int(gen), sub))
    return frames


def render_gif(
    grid: np.ndarray,
    grid_h: int,
    grid_w: int,
    lower: int,
    bits: int,
    frames: list[tuple[int, pd.DataFrame]],
    figures_dir: str,
    algo: str,
    case_name: str,
) -> None:
    if not frames:
        print(f"  skip {algo}/{case_name}: no frames")
        return

    upper = bits - lower
    fig, ax = plt.subplots(figsize=(8, 8))
    ax.imshow(grid, cmap="viridis", origin="lower", aspect="equal")
    overlay_img = ax.imshow(np.zeros((grid_h, grid_w, 4)), origin="lower", aspect="equal")
    title = ax.set_title("")
    ax.set_xlabel(f"Lower {lower} bits")
    ax.set_ylabel(f"Upper {upper} bits")

    def update(frame_idx):
        gen, popdf = frames[frame_idx]
        pop_grid = np.zeros((grid_h, grid_w))
        for _, row in popdf.iterrows():
            idx = int(float(row["id"]))
            if idx < 0 or idx >= (1 << bits):
                continue
            pop_grid[idx >> lower, idx & ((1 << lower) - 1)] += 1
        pop_smooth = gaussian_filter(pop_grid, sigma=2)
        mx = pop_smooth.max()
        pop_alpha = np.where(
            pop_smooth > 0.01,
            np.clip(pop_smooth / mx, 0.15, 0.7) if mx > 0 else 0,
            0,
        )
        red_overlay = np.zeros((grid_h, grid_w, 4))
        red_overlay[..., 0] = 1.0
        red_overlay[..., 3] = pop_alpha
        overlay_img.set_data(red_overlay)
        title.set_text(f"{algo.upper()} — {case_name} — generation {gen}")
        return [overlay_img, title]

    anim = FuncAnimation(fig, update, frames=len(frames), interval=500, blit=True)
    os.makedirs(figures_dir, exist_ok=True)
    out_path = os.path.join(figures_dir, f"anim_{algo}_{case_name}.gif")
    anim.save(out_path, writer="pillow", fps=2)
    plt.close()
    print(f"  saved {out_path}")


def process_case(case: dict, figures_dir: str) -> None:
    name = case["name"]
    bits = case["bits"]
    fit_col = case["fit_col"]
    land = case["landscape"]
    if not os.path.isfile(land):
        print(f"  skip all animations for {name}: missing landscape {land}")
        return

    grid, gh, gw, lower = landscape_grid(land, bits, fit_col)

    for algo, key in (
        ("nsga2", "nsga_snapshots"),
        ("pso", "pso_snapshots"),
        ("sga", None),
    ):
        if algo == "sga":
            fr = frames_from_sga(case["sga_anim_dir"], name)
        else:
            fr = frames_from_snapshots(case[key])
        render_gif(grid, gh, gw, lower, bits, fr, figures_dir, algo, name)


def main():
    p = argparse.ArgumentParser(description="GIFs: NSGA-II, PSO, SGA × 4 datasets.")
    p.add_argument("--figures-dir", default="figures", help="Output directory for GIFs")
    args = p.parse_args()

    for case in CASES:
        print(f"Case {case['name']}:")
        process_case(case, args.figures_dir)


if __name__ == "__main__":
    main()
